week7/employee_management/employee/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path

from employee import views
urlpatterns = [
    # ex: /employee/
    path("", views.IndexView.as_view(), name="employee"),
    # ex: /employee/5/
    path("positon/", views.PositionView.as_view(), name="positon"),
    # ex: /employee/5/vote/
    path("project/", views.PojectView.as_view(), name="project"),
    # ex: /employee/5/vote/
    path("project/<int:project_id>/", views.PojectdetailView.as_view(), name="projectdetail"),
    path("project/<int:id>/delete/", views.PojectView.as_view(), name="projectdel"),
    path("project/<int:project_id>/add_staff/<int:emp_id>/", views.PojectdetailView.as_view(), name="add_staff"),
    path("project/<int:project_id>/delete_staff/<int:emp_id>/", views.PojectdetailView.as_view(), name="delete_staff"),

]

week7/employee_management/employee_management/urls.py
from django.contrib import admin
from django.urls import path, include

from employee import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("employee/", include("employee.urls")),
]

week7/employee_management/employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    class Gender(models.Choices):
        M = "M"
        F = "F"
        LGBT = "LGBT"
        
    first_name = models.CharField(max_length=155)
    last_name = models.CharField(max_length=155)
    gender = models.CharField(max_length=10, choices=Gender.choices)
    birth_date = models.DateField()
    hire_date = models.DateField()
    salary = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    position = models.ForeignKey(
        "employee.Position", 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )
    
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

class EmployeeAddress(models.Model):
    employee = models.OneToOneField("employee.Employee", on_delete=models.PROTECT)
    location = models.TextField(null=True, blank=True)
    district = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=15)
    
    
class Department(models.Model):
    name = models.CharField(max_length=155)
    manager = models.OneToOneField(
        "employee.Employee", 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )
    
class Position(models.Model):
    name = models.CharField(max_length=155)
    description = models.TextField(null=True, blank=True)
    department = models.ForeignKey(
        "employee.Department",
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )

class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    manager = models.OneToOneField(
        "employee.Employee", 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name="project_mamager"
    )
    due_date = models.DateField()
    start_date = models.DateField()
    staff = models.ManyToManyField("employee.Employee")

week7/employee_management/employee/views.py
from django.shortcuts import render , redirect
import json
from django.http import HttpResponse
from .models import *
from django.views import View
from django.http import JsonResponse

# Create your views here.

class IndexView(View):

    def get(self, request):
        employee_list = Employee.objects.order_by("id")
        num  = Employee.objects.count()
        context = {
            "employee_list" : employee_list,
            "num" : num       
                   }
        return render(request, "employee.html", context)
    
class PositionView(View):
    def get(self, request):
        position_list = Position.objects.order_by("id")
        context = {
            "position_list" : position_list, 
                   }
        return render(request, "position.html", context)
    
    
class PojectView(View):
    def get(self, request):
        project_list = Project.objects.order_by("id")
        context = {
            "project_list" : project_list
                   }
        return render(request, "project.html", context)
    def delete(self, request, id):
        project = Project.objects.get(pk=id)
        project.delete()
        return JsonResponse({'foo':'bar'}, status=200)
    
    
    
    # def post (self, request, project_id):
    #     project = Project.objects.get(pk=project_id).delete()
    #     return render("project", "project_detail.html")
    
class PojectdetailView(View):
    def get (self, request, project_id):
        project = Project.objects.get(pk=project_id)
        context = {
            "project" : project,
            "start_date" : project.start_date.strftime("%Y-%m-%d"),
            "due_date" : project.due_date.strftime("%Y-%m-%d"),
                   }
        return render(request, "project_detail.html", context)
    
    def put(self, request, project_id, emp_id):
        try:
            
            project = Project.objects.get(id=project_id)
            employee = Employee.objects.get(id=emp_id)

            # Add employee to project
            project.staff.add(employee)
            return JsonResponse({'message': 'Employee added successfully'})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)
        
    def delete(self, request, project_id, emp_id):
        try: 
            project = Project.objects.get(id=project_id)
            employee = Employee.objects.get(id=emp_id)
            project.staff.remove(employee)
            return JsonResponse({"message": "Project deleted successfully."}, status=200)
        except Project.DoesNotExist:
            return JsonResponse({"error": "Project not found."}, status=404)

week7/employee_management/employee/templates/employee.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}  <!-- สำหรับการแสดงผลเงินเดือนด้วย comma -->
{% block title %}
    Employee
{% endblock %}

{% block nav %}
{% include 'nav.html' %}
{% endblock %}

{% block content %}
    <div class="head">
        <h1>Employee</h1>
        <div>
            <h1>Total {{ num }} People</h1>
        </div>
    </div>

    <table> 
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Gender</th>
                <th>Birth Date</th>
                <th>Hire Date</th>
                <th>Salary</th>
                <th>Department</th>
                <th>Position</th>
            </tr>
        </thead>

        <tbody>
                {% for employee in employee_list %}
                <tr style="{% if forloop.first or forloop.last %}color: red;{% endif %}">
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.first_name }} {{ employee.last_name }}</td>
                    <td>
                        {% if employee.gender == 'M' %}Male
                        {% elif employee.gender == 'F' %}Female
                        {% else %}Other{% endif %}
                    </td>
                    <td>{{ employee.birth_date|date:"d/m/Y" }}</td>
                    <td>{{ employee.hire_date|date:"d/m/Y" }}</td>
                    <td>{{ employee.salary|intcomma }}</td>
                    <td>{{ employee.position.department.name }}</td>
                    <td>{{ employee.position.name }}</td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}

week7/employee_management/employee/templates/layout.html
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block nav %}
        {% include 'nav.html' %}
    {% endblock %}
    {% block header %}{% endblock %}
    <main>
        {% block content %}{% endblock %}
    </main>
    {% block script %}
        <script src="{% static "manage_staff.js" %}"></script>
        <script src="{% static "project.js" %}"></script>
    {% endblock %}
</body>
</html>

week7/employee_management/employee/templates/nav.html
{% extends "layout.html" %}
{% block nav %}
    <header>
        <nav>
            <a href="{% url 'project' %}">Project</a>
            <a href="{% url 'employee' %}">Employee</a>
            <a href="{% url 'positon' %}">Position</a>
        </nav>
    </header>
{% endblock %}

week7/employee_management/employee/templates/position.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Position
{% endblock %}

{% block content %}
    <div class="head">
        <h1>Position</h1>
    </div>
    
    <div class="itemGroup">
        {% for position in position_list %}
        <div class="item">
            <div>{{ position.id }}. {{ position.name }}</div>
            <div class="action">{{ position.employee_set.count }} People</div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    
    <!-- คุณสามารถเพิ่มสคริปต์พิเศษที่ใช้ในหน้านี้ได้ที่นี่ -->
{% endblock %}

week7/employee_management/employee/templates/project.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
    Project
{% endblock %}

{% block content %}
    <div class="head">
        <h1>Project</h1>
    </div>

    <div class="itemGroup">
        {% for project in project_list %}
        <div class="item">
            <div>{{ project.id }}. {{ project.name }}</div>
            <div>{{ project.start_date }} - {{ project.due_date }}</div>

            <div class="action">
                <a href="{% url 'projectdetail' project.id %}" class="edit btn">แก้ไข</a>
                <button type="submit" onclick="deleteProject({{ project.id }},'{{csrf_token}}')" class="delete">Delete</button>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
        src="{% static "project.js" %}}"
    </script>
{% endblock %}

week7/employee_management/employee/templates/project_detail.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
    Project Detail
{% endblock %}

{% block content %}
    <div>
        <h1>Project Detail</h1>

        <form class="form" id="project-form" method="post" style="margin-top: 15px;">
            <label for="">Project Name</label>
            <input type="text" placeholder="project name" value="{{ project.name }}">
            
            <label for="">Description</label>
            <textarea placeholder="description" rows="4">{{ project.description }}</textarea>

            <label for="">Start Date</label>
            <input 
                type="date" 
                placeholder="start-date"
                style="width: 150px;" 
                value="{{ start_date }}" 
            >
            <label for="">Due Date</label>
            <input 
                type="date" 
                placeholder="due-date" 
                style="width: 150px;" 
                value="{{ due_date }}"
            >

            <label for="">Project Manager</label>
            <select style="width: 320px; height: 30px;">
                <option value="{{ project.manager.id }}">{{ project.manager.first_name }} {{ project.manager.last_name }}</option>
            </select>
        </form>
    </div>

    <br />
    <br />

    <div>
        <div class="head">
            <h2>Employee in this project</h2>

            <div class="action">
                <div id="add-staff">
                    <input type="text" name="emp_id" id="input-add-staff" placeholder="EMPLOYEE ID">
                    <button type="submit" onclick="addStaff({{ project.id }} , '{{csrf_token}}')">ADD</button>
                </div>
            </div>
        </div>
        <div class="itemGroup">
            {% for staff in project.staff.all %}
            <div class="item">
                <div>ID.{{ staff.id }} Full Name {{ staff.first_name }} {{ staff.lastname }}</div>
                <div>Position {{ staff.position.name }}</div>
                <div class="action">
                    <button type="submit" class="delete" onclick="removeStaff({{ project.id }}, {{ staff.id }}, '{{csrf_token}}')">
                        Kick this Staff
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'manage_staff.js' %}"></script>
{% endblock %}